#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for backend/affinty
#
# IDENTIFICATION
#    src/backend/affinty/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/affinty
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = affinty.o

include $(top_srcdir)/src/backend/common.mk

