#-------------------------------------------------------------------------
#
# Makefile for backend/affinity/utils
#
# IDENTIFICATION
#    src/backend/affinity/utils/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/affinity/utils
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = hash64.o

include $(top_srcdir)/src/backend/common.mk

