#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for backend/affinity
#
# IDENTIFICATION
#    src/backend/affinity/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/affinity
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = affinity.o

SUBDIRS = utils

include $(top_srcdir)/src/backend/common.mk

